from __future__ import annotations

import os
import pickle
from pathlib import Path

CREDENTIALS_PATH = Path.home() / ".basketball-analyzer" / "youtube_credentials.pickle"
SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]


def authenticate() -> object:
    """Run OAuth 2.0 flow and persist credentials. Opens a browser window."""
    from google_auth_oauthlib.flow import InstalledAppFlow  # type: ignore

    secrets_file = os.environ.get("YOUTUBE_CLIENT_SECRETS_FILE", "client_secrets.json")
    if not Path(secrets_file).exists():
        raise FileNotFoundError(
            f"YouTube client secrets not found: {secrets_file}\n"
            "Download OAuth 2.0 credentials from Google Cloud Console and set "
            "YOUTUBE_CLIENT_SECRETS_FILE env var."
        )

    flow = InstalledAppFlow.from_client_secrets_file(secrets_file, SCOPES)
    credentials = flow.run_local_server(port=0)
    CREDENTIALS_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(CREDENTIALS_PATH, "wb") as f:
        pickle.dump(credentials, f)
    return credentials


def _load_credentials() -> object | None:
    if CREDENTIALS_PATH.exists():
        with open(CREDENTIALS_PATH, "rb") as f:
            return pickle.load(f)
    return None


class YouTubeUploader:
    def __init__(self) -> None:
        from googleapiclient.discovery import build  # type: ignore

        creds = _load_credentials()
        if creds is None:
            raise RuntimeError(
                "YouTube not authenticated. Run: basketball-analyzer --youtube-auth"
            )
        self._youtube = build("youtube", "v3", credentials=creds)

    def upload(
        self,
        video_path: Path,
        title: str,
        description: str = "",
        tags: list[str] | None = None,
        privacy: str = "unlisted",
    ) -> str:
        from googleapiclient.http import MediaFileUpload  # type: ignore

        body = {
            "snippet": {
                "title": title[:100],
                "description": description,
                "tags": tags or ["basketball", "highlights", "sports"],
                "categoryId": "17",  # Sports
            },
            "status": {"privacyStatus": privacy},
        }
        media = MediaFileUpload(
            str(video_path),
            mimetype="video/mp4",
            resumable=True,
        )
        request = self._youtube.videos().insert(
            part=",".join(body.keys()), body=body, media_body=media
        )
        response = None
        while response is None:
            _, response = request.next_chunk()
        video_id = response["id"]
        return f"https://www.youtube.com/watch?v={video_id}"

    def upload_highlights(
        self,
        highlights: list,
        game_title: str,
        privacy: str = "unlisted",
    ) -> list[str]:
        urls: list[str] = []
        for i, seg in enumerate(highlights):
            clip = getattr(seg, "narrated_clip_path", None) or getattr(seg, "clip_path", None)
            if clip is None or not Path(clip).exists():
                continue
            title = f"{game_title} – Highlight #{i+1} | Basketball Analyzer"
            description = (
                f"Game: {game_title}\n"
                f"Timestamp: {seg.start_sec:.0f}s – {seg.end_sec:.0f}s\n"
                f"Excitement score: {seg.peak_excitement:.1f}\n\n"
                f"Generated by Basketball Analyzer"
            )
            url = self.upload(Path(clip), title, description, privacy=privacy)
            urls.append(url)
        return urls
